apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: roles-horizon
  namespace: roles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roles-horizon

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: roles-horizon
    spec:
      containers:
      - name: horizon
        image: ulrich2002/roles-manager:0.0.1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: laravel-config
        env:
        - name: START_HORIZON
          value: "true"
        - name: RUN_LARAVEL_CRON
          value: "false"
        - name: START_NGINX
          value: "false"

      imagePullSecrets:
      - name: docker-auth
