apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: roles-cron
  namespace: roles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roles-cron

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: roles-cron
    spec:
      containers:
      - name: cron
        image: your-docker-image
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: laravel-config
        env:
        - name: START_HORIZON
          value: "false"
        - name: RUN_LARAVEL_CRON
          value: "true"
        - name: START_NGINX
          value: "false"
        - name: START_PHP_FPM
          value: "false"

      imagePullSecrets:
      - name: docker-auth
